services:
  flask_app:
    container_name: flask_app
    image: toutanji/first_lab:1.0.0
    build: .
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:123@flask_db:5432/test
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata: {}
    
    

